### ISSUE TITLE
How to get working? 

### ISSUE THREAD

**Issue by LewisWildgoose** [2taken/autofishing#1]
Hey mate, thanks for creating this. I have the macro running in Pycharm but it doesn't actually seem to do anything in Destiny even after pressing the hotkey

https://i.imgur.com/iyeLS4D.jpeg

**Comment by LewisWildgoose** [comment]
Did some more playing around, it doesn't do anything when trying to fish, however if i pull out my ghost or get off my sparrow, it presses E to hop back on or spawn

**Comment by ilytaken** [comment]
you should change the capture dictionary in config. it is made for the tightest screen bounds. use photoshop rulers to measure pixels from screen borders. 

 first 2 define position of upper left corner of the rectangle and last 2 define its width and height.
 
 i guess then it will work.

**Comment by LewisWildgoose** [comment]
Haha nah it's no problem, so I just changed my resolution to match + set the tightest screen bounds possible. It's now working and holds E to cast and also catches, but it seems to catch as soon as the popup hits, so it's constantly catching nothing rather than waiting half a second for perfect catch. Hope this makes sense, if not I can drop a video

**Comment by ilytaken** [comment]
for me it works just fine, but i will ability to add delay.

**Comment by ilytaken** [comment]
shit added
